name: Renovate

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_8,11,14,17_*_*_*
    - cron: '0 8,11,14,17 * * *'

concurrency:
  group: renovate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-slim
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44.2.5
        with:
          configurationFile: 'renovate-self-hosted.json'
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|AWS_TOKEN)$"
          token: '${{ secrets.GH_TOKEN_BOT }}'
