name: Renovate

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_8,11,14,17_*_*_*
    - cron: '0 8,11,14,17 * * *'

concurrency:
  group: renovate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-slim
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@eaf12548c13069dcc28bb75c4ee4610cdbe400c5 # v44.2.6
        with:
          configurationFile: 'renovate-self-hosted.json'
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|AWS_TOKEN)$"
          token: '${{ secrets.ORY_BOT_PAT }}'
